apiVersion: v1
kind: ConfigMap
metadata:
  name: budget-tracker-transaction-configmap
  namespace: tracker
data:
  APP_SETTINGS: project.config.ProductionConfig
  DATABASE_URL: postgresql://postgres:7426@10.1.0.13:5432/budget_tracker_transaction

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-tracker-transaction
  namespace: tracker
spec:
  selector:
    matchLabels:
      app: budget-tracker-transaction
  template:
    metadata:
      labels:
        app: budget-tracker-transaction
    spec:
      containers:
        - name: budget-tracker-transaction
          image: simon7426/budget-tracker-transaction-prod:0.2
          envFrom:
            - configMapRef:
                name: budget-tracker-transaction-configmap
            - secretRef:
                name: secretkey
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: budget-tracker-transaction-service
  namespace: tracker
spec:
  selector:
    app: budget-tracker-transaction
  ports:
    - port: 8000
      targetPort: 8000
