version: "3.8"

services:
  auth:
    image: simon7426/budget-tracker-auth-prod:0.1
    container_name: budget-tracker-auth
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - SECRET_KEY=my_precious_tracker
      - DATABASE_URL=postgresql://postgres:7426@db:5432/budget_tracker_auth
      - DATABASE_TEST_URL=postgresql://postgres:7426@db:5432/budget_tracker_auth_test
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  transaction:
    image: simon7426/budget-tracker-transaction-prod:0.1
    container_name: budget-tracker-transaction
    environment:
      - APP_SETTINGS=project.config.ProductionConfig
      - SECRET_KEY=my_precious_tracker
      - DATABASE_URL=postgresql://postgres:7426@db:5432/budget_tracker_transaction
      - DATABASE_TEST_URL=postgresql://postgres:7426@db:5432/budget_tracker_transaction_test
    depends_on:
      - db

  profile:
    image: simon7426/budget-tracker-profile-prod:0.1
    container_name: budget-tracker-profile
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious_tracker
      - DATABASE_URL=postgresql://postgres:7426@db:5432/budget_tracker_profile
      - DATABASE_TEST_URL=postgresql://postgres:7426@db:5432/budget_tracker_profile_test
    depends_on:
      - db

  client:
    image: simon7426/budget-tracker-client-prod:0.1
    container_name: budget-tracker-client
    depends_on:
      - auth
      - transaction
      - profile

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    container_name: budget-tracker-db
    expose:
      - 5432
    volumes:
      - ./budget-tracker-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=7426

  redis:
    image: redis:6.2.6-alpine
    container_name: budget-tracker-redis
    expose:
      - 6379

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: budget-tracker-nginx
    volumes:
      - /home/ubuntu/certs/fullchain.pem:/usr/share/nginx/tracker.simonislam.com.crt
      - /home/ubuntu/certs/privkey.pem:/usr/share/nginx/tracker.simonislam.com.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - auth
      - transaction
      - profile
