"""initial migrations

Revision ID: 475b589348ff
Revises: 
Create Date: 2021-12-24 02:32:37.177538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '475b589348ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.Column('category_type', sa.Enum('income', 'expense', name='choicetype'), nullable=False),
    sa.Column('category_owner', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_owner', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('income', 'expense', name='choicetype'), nullable=False),
    sa.Column('transaction_description', sa.String(length=300), nullable=False),
    sa.Column('transaction_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_category_id'], ['transaction_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_list')
    op.drop_table('transaction_category')
    # ### end Alembic commands ###
