"""added account owner column to account transfer

Revision ID: 9694faf7782e
Revises: cd9107b53b39
Create Date: 2022-02-16 06:54:40.618776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9694faf7782e'
down_revision = 'cd9107b53b39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_account_transfer', sa.Column('account_owner', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_account_transfer', 'account_owner')
    # ### end Alembic commands ###
