"""empty message

Revision ID: adfc784f4f2e
Revises: 86554dfa950a
Create Date: 2022-10-06 07:02:25.120820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adfc784f4f2e'
down_revision = '86554dfa950a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_account_transfer', sa.Column('transfer_description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_account_transfer', 'transfer_description')
    # ### end Alembic commands ###
