"""changed column cost to amount

Revision ID: f4fb221fdb7d
Revises: 9694faf7782e
Create Date: 2022-02-16 07:12:11.603573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fb221fdb7d'
down_revision = '9694faf7782e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_account_transfer', sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('transaction_account_transfer', 'transfer_cost')
    op.add_column('transaction_list', sa.Column('transaction_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.drop_column('transaction_list', 'transaction_cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_list', sa.Column('transaction_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('transaction_list', 'transaction_amount')
    op.add_column('transaction_account_transfer', sa.Column('transfer_cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('transaction_account_transfer', 'transfer_amount')
    # ### end Alembic commands ###
